//
//  BenchmarkReportWriter.swift
//  BenchmarkRunner
//
//  Renders a `BenchmarkReport` as a markdown file. The format is
//  deliberately flat and line-diff-friendly so that CI can compare before
//  and after post-processing changes with `git diff --word-diff`.
//

import Foundation

struct BenchmarkReport {
    let label: String
    let matteFolder: URL
    let frameCount: Int
    let frameWidth: Int
    let frameHeight: Int
    let temporalMetrics: TemporalMetrics
    let runDuration: Duration
}

enum BenchmarkReportWriter {

    static func writeMarkdown(_ report: BenchmarkReport, to url: URL) throws {
        let parent = url.deletingLastPathComponent()
        try FileManager.default.createDirectory(at: parent, withIntermediateDirectories: true)
        try render(report).write(to: url, atomically: true, encoding: .utf8)
    }

    /// Returns the markdown body. Split out so tests can assert on structure
    /// without round-tripping through the filesystem.
    static func render(_ report: BenchmarkReport) -> String {
        let metrics = report.temporalMetrics
        let generatedAt = Date().formatted(.iso8601)

        var lines: [String] = []
        lines.append("# Corridor Key Toolbox — Matte Benchmark")
        lines.append("")
        lines.append("**Label:** \(report.label)")
        lines.append("**Matte folder:** `\(report.matteFolder.path(percentEncoded: false))`")
        lines.append("**Generated:** \(generatedAt)")
        lines.append("**Analysis duration:** \(report.runDuration.formattedSeconds)")
        lines.append("")
        lines.append("## Sequence")
        lines.append("")
        lines.append("| Metric | Value |")
        lines.append("| --- | --- |")
        lines.append("| Frames | \(report.frameCount) |")
        lines.append("| Resolution | \(report.frameWidth) × \(report.frameHeight) |")
        lines.append("")
        lines.append("## Temporal stability")
        lines.append("")
        lines.append("Lower is better. Edge-band values are restricted to pixels whose mean alpha is between 0.05 and 0.95 — the region where flicker is visually obvious.")
        lines.append("")
        lines.append("| Metric | Value |")
        lines.append("| --- | --- |")
        lines.append("| Global mean σ | \(formatFloat(metrics.globalMeanStdDev)) |")
        lines.append("| Edge-band mean σ | \(formatFloat(metrics.edgeBandMeanStdDev)) |")
        lines.append("| Edge-band p95 σ | \(formatFloat(metrics.edgeBandP95StdDev)) |")
        lines.append("| Edge-band max σ | \(formatFloat(metrics.edgeBandMaxStdDev)) |")
        lines.append("| Edge-band pixel share | \(formatPercent(metrics.edgeBandPixelPercentage)) |")
        lines.append("| Global mean α (sanity) | \(formatFloat(metrics.globalMeanAlpha)) |")
        lines.append("")
        lines.append("## Notes")
        lines.append("")
        lines.append("- This file is regenerated by `swift run BenchmarkRunner` against the matte folder above.")
        lines.append("- For a before/after comparison, run the tool against two label-distinguished folders (for example, `.../baseline` and `.../phase1-temporal`).")
        return lines.joined(separator: "\n") + "\n"
    }

    private static func formatFloat(_ value: Double) -> String {
        value.formatted(.number.precision(.fractionLength(5)))
    }

    private static func formatPercent(_ value: Double) -> String {
        value.formatted(.number.precision(.fractionLength(2))) + " %"
    }
}
